### ISSUE TITLE
'lofi' alias not working on macOS

### ISSUE THREAD

**Issue by Kyngo** [duhow/dotfiles#1]
**Expected behaviour:**

Running 'lofi' should execute
```
nohup vlc --one-instance --no-video https://www.youtube.com/watch\?v\=5qap5aO4i9A </dev/null &>/dev/null &
```
and open a VLC instance with music playing in the background.

**Current behaviour:**

Nothing happens. When running manually the command you get the following error:
```
VLC media player 3.0.7.1 Vetinari (revision 3.0.7.1-1-0-g26acdaa9ca)
vlc: unknown option or missing mandatory argument `--one-instance'
Try `vlc --help' for more information.
```

**Comment by duhow** [comment]
As per VLC wiki: 
> On the Mac, running multiple instances of VLC is not supported out of the box.

https://wiki.videolan.org/VLC_HowTo/Play_multiple_instances/

Also this dotfiles are most dedicated to Linux :( 
But still feel free to do a PR with the fix :)

**Comment by Kyngo** [comment]
Oh, crapbaskets.

I'll research for a macOS solution and make a PR indeed ;)
